---
- name: Configure MongoDB
  hosts: db
  tags: db-tag
  become: true
  vars:
    mongo_bind_ip: 0.0.0.0
  tasks:
    - name: Change mongo config file
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      notify: restart mongod

    - name: Get DB IP
      set_fact: db_ip="{{ item.networkIP }}"
      with_items: "{{ networkInterfaces }}"

  handlers:
  - name: restart mongod
    service: name=mongod state=restarted
...
