---
- name: Configure Deploy
  hosts: app
  tags: deploy-tag
  become: true
  tasks:
    - name: Fetch the latest version of app code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/appuser/reddit
        version: monolith
      tags: deploy-tag
      notify: reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/appuser/reddit
      tags: deploy-tag
  handlers:
  - name: reload puma
    systemd: name=puma state=restarted
...
